import {Component, OnInit} from '@angular/core';
import {TranslateService} from "@ngx-translate/core";

@Component({
  selector: 'app-branches',
  templateUrl: './branches.component.html',
  styleUrls: ['./branches.component.scss']
})
export class BranchesComponent implements OnInit {
  tabsArray: string[] = ['aboutBranchesPageTextNineteen', 'aboutBranchesPageTextTwenty', 'aboutBranchesPageTextTwentyOne', 'aboutBranchesPageTextTwentyTwo'];
  activatedTab: number = 0;

  constructor(private translate: TranslateService) {
  }

  translateText(key: string) : string {
    return this.translate.instant(key);
  }

  ngOnInit() {
  }

  setTab(index: number) {
    this.activatedTab = index;
  }
  customMarkerIcon: any  = {
    url: './assets/images/pages/about/location/branch.png',
    scaledSize: {
      width: 35,
      height: 40
    }
  };

  branchOptions: google.maps.MapOptions = {
    styles: [
      {
        featureType: 'landscape',
        elementType: 'geometry',
        stylers: [
          {hue: '#686868'},
          {saturation: 0},
          {lightness: 0}
        ]
      },
      {
        featureType: 'road',
        elementType: 'labels.text.fill',
        stylers: [
          {color: '#2c2c2c'}
        ]
      },
      {
        featureType: 'buildings',
        elementType: 'geometry',
        stylers: [
          {hue: '#686868'},
          {saturation: -100},
          {lightness: 0}

        ]
      },
      {
        featureType: 'poi',
        stylers: [
          {visibility: 'off'}
        ]
      },
    ]
  };

  dushanbe = [
    {
      title: 'aboutBranchAddressInfoOne',
      address: 'aboutBranchesPageTextNine',
      translatedAddress: 'aboutBranchesPageTextNine',
      lat: 38.56189522986055,
      lng: 68.78508842680635,
      addressTitle: 'aboutBranchesPageTextEight',
      workingGraphic: "aboutBranchesPageTextTen",
      workingGraphicWorkingDays: "aboutBranchesPageTextEleven",
      workingGraphicDaysOff: "aboutBranchesPageTextTwelve",
      contacts: "aboutBranchesPageTextThirteen",
      contactsEmail: "aboutBranchesPageTextFifteen",
      services: "aboutBranchesPageTextSixteen",
      service: "aboutBranchesPageTextSeventeen",
    },
    {
      title: 'aboutBranchAddressInfoTwo',
      address: 'г. Душанбе, р-н. Фирдавси ул. А.Кахоров 75',
      translatedAddress: 'aboutBranchAddressInfoFour',
      lat: 38.551445493177454,
      lng: 68.7724729233923,
      addressTitle: 'aboutBranchesPageTextEight',
      workingGraphic: "aboutBranchesPageTextTen",
      workingGraphicWorkingDays: "aboutBranchesPageTextEleven",
      workingGraphicDaysOff: "aboutBranchesPageTextTwelve",
      contacts: "aboutBranchesPageTextThirteen",
      contactsEmail: "aboutBranchesPageTextFifteen",
      services: "aboutBranchesPageTextSixteen",
      service: "aboutBranchesPageTextSeventeen",
    },
    {
      title: 'aboutBranchAddressInfoThree',
      address: 'г. Душанбе, р-н. И. Сомони, пр. Рудаки 127',
      translatedAddress: 'aboutBranchAddressInfoFive',
      lat: 38.59620676769875,
      lng: 68.78644512922176,
      addressTitle: 'aboutBranchesPageTextEight',
      workingGraphic: "aboutBranchesPageTextTen",
      workingGraphicWorkingDays: "aboutBranchesPageTextEleven",
      workingGraphicDaysOff: "aboutBranchesPageTextTwelve",
      contacts: "aboutBranchesPageTextThirteen",
      contactsEmail: "aboutBranchesPageTextFifteen",
      services: "aboutBranchesPageTextSixteen",
      service: "aboutBranchesPageTextSeventeen",
    },
    {
      title: 'aboutBranchAddressInfoThree',
      address: 'г. Душанбе р-н.Шохмансур, ул. М. Мастонгулова 32/2, (Терминали №1 международный Аэропорт)',
      translatedAddress: 'aboutBranchAddressInfoSix',
      lat: 38.55774884481649,
      lng: 68.80793773813296,
      addressTitle: 'aboutBranchesPageTextEight',
      workingGraphic: "aboutBranchesPageTextTen",
      workingGraphicWorkingDays: "aboutBranchesPageTextEleven",
      workingGraphicDaysOff: "aboutBranchesPageTextTwelve",
      contacts: "aboutBranchesPageTextThirteen",
      contactsEmail: "aboutBranchesPageTextFifteen",
      services: "aboutBranchesPageTextSixteen",
      service: "aboutBranchesPageTextSeventeen",
    },
  ]

  drs = [
    {
      title: 'aboutBranchAddressInfoTwo',
      address: 'р-н. Рудаки, пос. Сомониён, ул. Пушкина 42 А',
      translatedAddress: 'aboutBranchAddressInfoSeven',
      lat: 38.44217571403086,
      lng: 68.77431617020443,
      addressTitle: 'aboutBranchesPageTextEight',
      workingGraphic: "aboutBranchesPageTextTen",
      workingGraphicWorkingDays: "aboutBranchesPageTextEleven",
      workingGraphicDaysOff: "aboutBranchesPageTextTwelve",
      contacts: "aboutBranchesPageTextThirteen",
      contactsEmail: "aboutBranchesPageTextFifteen",
      services: "aboutBranchesPageTextSixteen",
      service: "aboutBranchesPageTextSeventeen",
    },
    {
      title: 'aboutBranchAddressInfoThree',
      address: 'р-н. Рудаки, пос. Сомониён, ул. И.Сомони 61',
      translatedAddress: 'aboutBranchAddressInfoEight',
      lat: 38.44081604051886,
      lng:  68.77410178489158,
      addressTitle: 'aboutBranchesPageTextEight',
      workingGraphic: "aboutBranchesPageTextTen",
      workingGraphicWorkingDays: "aboutBranchesPageTextEleven",
      workingGraphicDaysOff: "aboutBranchesPageTextTwelve",
      contacts: "aboutBranchesPageTextThirteen",
      contactsEmail: "aboutBranchesPageTextFifteen",
      services: "aboutBranchesPageTextSixteen",
      service: "aboutBranchesPageTextSeventeen",
    },
    {
      title: 'aboutBranchAddressInfoThree',
      address: 'р-н. Рудаки, ул. И. Сомони рынок «Сафина»',
      translatedAddress: 'aboutBranchAddressInfoNine',
      lat: 38.442505341233165,
      lng: 68.77612346578225,
      addressTitle: 'aboutBranchesPageTextEight',
      workingGraphic: "aboutBranchesPageTextTen",
      workingGraphicWorkingDays: "aboutBranchesPageTextEleven",
      workingGraphicDaysOff: "aboutBranchesPageTextTwelve",
      contacts: "aboutBranchesPageTextThirteen",
      contactsEmail: "aboutBranchesPageTextFifteen",
      services: "aboutBranchesPageTextSixteen",
      service: "aboutBranchesPageTextSeventeen",
    },
    {
      title: 'aboutBranchAddressInfoThree',
      address: 'р-н. Рудаки, ул. И. Сомони рынок «Гандж»',
      translatedAddress: 'aboutBranchAddressInfoTen',
      lat: 38.44061611917932,
      lng: 68.7722295024488,
      addressTitle: 'aboutBranchesPageTextEight',
      workingGraphic: "aboutBranchesPageTextTen",
      workingGraphicWorkingDays: "aboutBranchesPageTextEleven",
      workingGraphicDaysOff: "aboutBranchesPageTextTwelve",
      contacts: "aboutBranchesPageTextThirteen",
      contactsEmail: "aboutBranchesPageTextFifteen",
      services: "aboutBranchesPageTextSixteen",
      service: "aboutBranchesPageTextSeventeen",
    },
    {
      title: 'aboutBranchAddressInfoThree',
      address: 'р-н. Рудаки, джамоат М.Турсунзода, кишлак Элок магазин 39',
      translatedAddress: 'aboutBranchAddressInfoEleven',
      lat: 38.48864331548067,
      lng: 68.78417191555036,
      addressTitle: 'aboutBranchesPageTextEight',
      workingGraphic: "aboutBranchesPageTextTen",
      workingGraphicWorkingDays: "aboutBranchesPageTextEleven",
      workingGraphicDaysOff: "aboutBranchesPageTextTwelve",
      contacts: "aboutBranchesPageTextThirteen",
      contactsEmail: "aboutBranchesPageTextFifteen",
      services: "aboutBranchesPageTextSixteen",
      service: "aboutBranchesPageTextSeventeen",
    },
    {
      title: 'aboutBranchAddressInfoThree',
      address: 'г. Вахдат, ул. Фирдавси 45',
      translatedAddress: 'aboutBranchAddressInfoTwelve',
      lat: 38.51644193923049,
      lng: 68.72903455531606,
      addressTitle: 'aboutBranchesPageTextEight',
      workingGraphic: "aboutBranchesPageTextTen",
      workingGraphicWorkingDays: "aboutBranchesPageTextEleven",
      workingGraphicDaysOff: "aboutBranchesPageTextTwelve",
      contacts: "aboutBranchesPageTextThirteen",
      contactsEmail: "aboutBranchesPageTextFifteen",
      services: "aboutBranchesPageTextSixteen",
      service: "aboutBranchesPageTextSeventeen",
    },
    {
      title: 'aboutBranchAddressInfoThree',
      address: 'г. Турсунзода, ул. Б.Гафуров б/н (рынок “Баракат”)',
      translatedAddress: 'aboutBranchAddressInfoThirteen',
      lat: 38.51015026394243,
      lng: 68.23403628253031,
      addressTitle: 'aboutBranchesPageTextEight',
      workingGraphic: "aboutBranchesPageTextTen",
      workingGraphicWorkingDays: "aboutBranchesPageTextEleven",
      workingGraphicDaysOff: "aboutBranchesPageTextTwelve",
      contacts: "aboutBranchesPageTextThirteen",
      contactsEmail: "aboutBranchesPageTextFifteen",
      services: "aboutBranchesPageTextSixteen",
      service: "aboutBranchesPageTextSeventeen",
    },
    {
      title: 'aboutBranchAddressInfoThree',
      address: 'г. Турсунзода, ул. Б.Гафуров (станция ЖД)',
      translatedAddress: 'aboutBranchAddressInfoFourteen',
      lat: 38.51012676398436,
      lng: 68.23386087525601,
      addressTitle: 'aboutBranchesPageTextEight',
      workingGraphic: "aboutBranchesPageTextTen",
      workingGraphicWorkingDays: "aboutBranchesPageTextEleven",
      workingGraphicDaysOff: "aboutBranchesPageTextTwelve",
      contacts: "aboutBranchesPageTextThirteen",
      contactsEmail: "aboutBranchesPageTextFifteen",
      services: "aboutBranchesPageTextSixteen",
      service: "aboutBranchesPageTextSeventeen",
    },
    {
      title: 'aboutBranchAddressInfoThree',
      address: 'г. Турсунзода, ул. П.Тоджиев',
      translatedAddress: 'aboutBranchAddressInfoFifteen',
      lat: 38.513386,
      lng: 68.233606,
      addressTitle: 'aboutBranchesPageTextEight',
      workingGraphic: "aboutBranchesPageTextTen",
      workingGraphicWorkingDays: "aboutBranchesPageTextEleven",
      workingGraphicDaysOff: "aboutBranchesPageTextTwelve",
      contacts: "aboutBranchesPageTextThirteen",
      contactsEmail: "aboutBranchesPageTextFifteen",
      services: "aboutBranchesPageTextSixteen",
      service: "aboutBranchesPageTextSeventeen",
    },
    {
      title: 'aboutBranchAddressInfoThree',
      address: 'г. Турсунзода, ул. И.Сомони, ТЦ "Детский мир"',
      translatedAddress: 'aboutBranchAddressInfoSixteen',
      lat: 38.51082905993192,
      lng: 68.23378072716018,
      addressTitle: 'aboutBranchesPageTextEight',
      workingGraphic: "aboutBranchesPageTextTen",
      workingGraphicWorkingDays: "aboutBranchesPageTextEleven",
      workingGraphicDaysOff: "aboutBranchesPageTextTwelve",
      contacts: "aboutBranchesPageTextThirteen",
      contactsEmail: "aboutBranchesPageTextFifteen",
      services: "aboutBranchesPageTextSixteen",
      service: "aboutBranchesPageTextSeventeen",
    },
  ]

  sogd = [
    {
      title: 'aboutBranchAddressInfoTwo',
      address: 'г. Худжанд, ул. К. Худжанди 165',
      translatedAddress: 'aboutBranchAddressInfoSeventeen',
      lat: 40.28156761785792,
      lng: 69.62303701427719,
      addressTitle: 'aboutBranchesPageTextEight',
      workingGraphic: "aboutBranchesPageTextTen",
      workingGraphicWorkingDays: "aboutBranchesPageTextEleven",
      workingGraphicDaysOff: "aboutBranchesPageTextTwelve",
      contacts: "aboutBranchesPageTextThirteen",
      contactsEmail: "aboutBranchesPageTextFifteen",
      services: "aboutBranchesPageTextSixteen",
      service: "aboutBranchesPageTextSeventeen",
    },
    {
      title: 'aboutBranchAddressInfoThree',
      address: 'р-н. Зафаробод, ул. Уротеппа д. б/н',
      translatedAddress: 'aboutBranchAddressInfoEighteen',
      lat: 40.18372038994417,
      lng: 68.85646230817353,
      addressTitle: 'aboutBranchesPageTextEight',
      workingGraphic: "aboutBranchesPageTextTen",
      workingGraphicWorkingDays: "aboutBranchesPageTextEleven",
      workingGraphicDaysOff: "aboutBranchesPageTextTwelve",
      contacts: "aboutBranchesPageTextThirteen",
      contactsEmail: "aboutBranchesPageTextFifteen",
      services: "aboutBranchesPageTextSixteen",
      service: "aboutBranchesPageTextSeventeen",
    },
    {
      title: 'aboutBranchAddressInfoThree',
      address: 'пос. Зарнисор, ул. Сомониён 22',
      translatedAddress: 'aboutBranchAddressInfoNineteen',
      lat: 40.648154585648705,
      lng: 69.59697737186997,
      addressTitle: 'aboutBranchesPageTextEight',
      workingGraphic: "aboutBranchesPageTextTen",
      workingGraphicWorkingDays: "aboutBranchesPageTextEleven",
      workingGraphicDaysOff: "aboutBranchesPageTextTwelve",
      contacts: "aboutBranchesPageTextThirteen",
      contactsEmail: "aboutBranchesPageTextFifteen",
      services: "aboutBranchesPageTextSixteen",
      service: "aboutBranchesPageTextSeventeen",
    },
    {
      title: 'aboutBranchAddressInfoThree',
      address: 'р-н. Ашт пос. Шайдон, ул. И.Сомони д. б/н',
      translatedAddress: 'aboutBranchAddressInfoTwenty',
      lat: 40.66432771565648,
      lng: 70.35635373698958,
      addressTitle: 'aboutBranchesPageTextEight',
      workingGraphic: "aboutBranchesPageTextTen",
      workingGraphicWorkingDays: "aboutBranchesPageTextEleven",
      workingGraphicDaysOff: "aboutBranchesPageTextTwelve",
      contacts: "aboutBranchesPageTextThirteen",
      contactsEmail: "aboutBranchesPageTextFifteen",
      services: "aboutBranchesPageTextSixteen",
      service: "aboutBranchesPageTextSeventeen",
    },
    {
      title: 'aboutBranchAddressInfoThree',
      address: 'г. Конибодом, ул. И.Сомони 187',
      translatedAddress: 'aboutBranchAddressInfoTwentyOne',
      lat: 40.29154416984028,
      lng: 70.42557297996338,
      addressTitle: 'aboutBranchesPageTextEight',
      workingGraphic: "aboutBranchesPageTextTen",
      workingGraphicWorkingDays: "aboutBranchesPageTextEleven",
      workingGraphicDaysOff: "aboutBranchesPageTextTwelve",
      contacts: "aboutBranchesPageTextThirteen",
      contactsEmail: "aboutBranchesPageTextFifteen",
      services: "aboutBranchesPageTextSixteen",
      service: "aboutBranchesPageTextSeventeen",
    },
    {
      title: 'aboutBranchAddressInfoThree',
      address: 'р-н. Ашт, джамоат Ашт, пос. Дусти',
      translatedAddress: 'aboutBranchAddressInfoTwentyTwo',
      lat: 40.7454251416812,
      lng: 70.6532405865697,
      addressTitle: 'aboutBranchesPageTextEight',
      workingGraphic: "aboutBranchesPageTextTen",
      workingGraphicWorkingDays: "aboutBranchesPageTextEleven",
      workingGraphicDaysOff: "aboutBranchesPageTextTwelve",
      contacts: "aboutBranchesPageTextThirteen",
      contactsEmail: "aboutBranchesPageTextFifteen",
      services: "aboutBranchesPageTextSixteen",
      service: "aboutBranchesPageTextSeventeen",
    },
    {
      title: 'aboutBranchAddressInfoThree',
      address: 'р-н. дж.Расулов, пос. Мехробод, рынок “Ашроф”',
      translatedAddress: 'aboutBranchAddressInfoTwentyThree',
      lat: 40.15844329527259,
      lng: 69.52216163672212,
      addressTitle: 'aboutBranchesPageTextEight',
      workingGraphic: "aboutBranchesPageTextTen",
      workingGraphicWorkingDays: "aboutBranchesPageTextEleven",
      workingGraphicDaysOff: "aboutBranchesPageTextTwelve",
      contacts: "aboutBranchesPageTextThirteen",
      contactsEmail: "aboutBranchesPageTextFifteen",
      services: "aboutBranchesPageTextSixteen",
      service: "aboutBranchesPageTextSeventeen",
    },
    {
      title: 'aboutBranchAddressInfoThree',
      address: 'г. Пенджикент, ул. Рудаки 130',
      translatedAddress: 'aboutBranchAddressInfoTwentyFour',
      lat:  39.49702589981844,
      lng: 67.61126435717992,
      addressTitle: 'aboutBranchesPageTextEight',
      workingGraphic: "aboutBranchesPageTextTen",
      workingGraphicWorkingDays: "aboutBranchesPageTextEleven",
      workingGraphicDaysOff: "aboutBranchesPageTextTwelve",
      contacts: "aboutBranchesPageTextThirteen",
      contactsEmail: "aboutBranchesPageTextFifteen",
      services: "aboutBranchesPageTextSixteen",
      service: "aboutBranchesPageTextSeventeen",
    },
    {
      title: 'aboutBranchAddressInfoThree',
      address: 'р-н.Спитамен, пос. Нов, ул. Ленин, д. б/н',
      translatedAddress: 'aboutBranchAddressInfoTwentyFive',
      lat: 40.51727262860877,
      lng: 69.32952989304242,
      addressTitle: 'aboutBranchesPageTextEight',
      workingGraphic: "aboutBranchesPageTextTen",
      workingGraphicWorkingDays: "aboutBranchesPageTextEleven",
      workingGraphicDaysOff: "aboutBranchesPageTextTwelve",
      contacts: "aboutBranchesPageTextThirteen",
      contactsEmail: "aboutBranchesPageTextFifteen",
      services: "aboutBranchesPageTextSixteen",
      service: "aboutBranchesPageTextSeventeen",
    },
    {
      title: 'aboutBranchAddressInfoThree',
      address: 'р-н. Масчох, пос. Бустон, ул. И.Сомони д. б/н',
      translatedAddress: 'aboutBranchAddressInfoTwentySix',
      lat: 40.517280789649625,
      lng: 69.32954516611875,
      addressTitle: 'aboutBranchesPageTextEight',
      workingGraphic: "aboutBranchesPageTextTen",
      workingGraphicWorkingDays: "aboutBranchesPageTextEleven",
      workingGraphicDaysOff: "aboutBranchesPageTextTwelve",
      contacts: "aboutBranchesPageTextThirteen",
      contactsEmail: "aboutBranchesPageTextFifteen",
      services: "aboutBranchesPageTextSixteen",
      service: "aboutBranchesPageTextSeventeen",
    },
    {
      title: 'aboutBranchAddressInfoThree',
      address: 'г. Истаравшан, пр. И.Сомони, д. б/н',
      translatedAddress: 'aboutBranchAddressInfoTwentySeven',
      lat: 39.90268781999013,
      lng: 69.00094544013601,
      addressTitle: 'aboutBranchesPageTextEight',
      workingGraphic: "aboutBranchesPageTextTen",
      workingGraphicWorkingDays: "aboutBranchesPageTextEleven",
      workingGraphicDaysOff: "aboutBranchesPageTextTwelve",
      contacts: "aboutBranchesPageTextThirteen",
      contactsEmail: "aboutBranchesPageTextFifteen",
      services: "aboutBranchesPageTextSixteen",
      service: "aboutBranchesPageTextSeventeen",
    },
  ]

  khatlon = [
    {
      title: 'aboutBranchAddressInfoTwo',
      address: 'г. Бохтар, ул. Норинов 6',
      translatedAddress: 'aboutBranchAddressInfoTwentyEight',
      lat: 37.834672724724285,
      lng: 68.7768289,
      addressTitle: 'aboutBranchesPageTextEight',
      workingGraphic: "aboutBranchesPageTextTen",
      workingGraphicWorkingDays: "aboutBranchesPageTextEleven",
      workingGraphicDaysOff: "aboutBranchesPageTextTwelve",
      contacts: "aboutBranchesPageTextThirteen",
      contactsEmail: "aboutBranchesPageTextFifteen",
      services: "aboutBranchesPageTextSixteen",
      service: "aboutBranchesPageTextSeventeen",
    },
    {
      title: 'aboutBranchAddressInfoThree',
      address: 'р-н. Дж. Балхи, пос. Исаев, ул. Сино 19 (ТЦ “Бахор”)',
      translatedAddress: 'aboutBranchAddressInfoTwentyNine',
      lat: 37.834576185947505,
      lng: 68.77680629223237,
      addressTitle: 'aboutBranchesPageTextEight',
      workingGraphic: "aboutBranchesPageTextTen",
      workingGraphicWorkingDays: "aboutBranchesPageTextEleven",
      workingGraphicDaysOff: "aboutBranchesPageTextTwelve",
      contacts: "aboutBranchesPageTextThirteen",
      contactsEmail: "aboutBranchesPageTextFifteen",
      services: "aboutBranchesPageTextSixteen",
      service: "aboutBranchesPageTextSeventeen",
    },
    {
      title: 'aboutBranchAddressInfoThree',
      address: 'р-н. Ёвон, ул. Комсомол (ТЦ “Саъдулло”)',
      translatedAddress: 'aboutBranchAddressInfoThirty',
      lat: 38.31789310128809,
      lng: 69.03685148502663,
      addressTitle: 'aboutBranchesPageTextEight',
      workingGraphic: "aboutBranchesPageTextTen",
      workingGraphicWorkingDays: "aboutBranchesPageTextEleven",
      workingGraphicDaysOff: "aboutBranchesPageTextTwelve",
      contacts: "aboutBranchesPageTextThirteen",
      contactsEmail: "aboutBranchesPageTextFifteen",
      services: "aboutBranchesPageTextSixteen",
      service: "aboutBranchesPageTextSeventeen",
    },
    {
      title: 'aboutBranchAddressInfoThree',
      address: 'р-н. Шахритуз, пос. Шахритуз ул. И. Сомони 6',
      translatedAddress: 'aboutBranchAddressInfoThirtyOne',
      lat: 37.265879793495756,
      lng: 68.14301297246037,
      addressTitle: 'aboutBranchesPageTextEight',
      workingGraphic: "aboutBranchesPageTextTen",
      workingGraphicWorkingDays: "aboutBranchesPageTextEleven",
      workingGraphicDaysOff: "aboutBranchesPageTextTwelve",
      contacts: "aboutBranchesPageTextThirteen",
      contactsEmail: "aboutBranchesPageTextFifteen",
      services: "aboutBranchesPageTextSixteen",
      service: "aboutBranchesPageTextSeventeen",
    },
    {
      title: 'aboutBranchAddressInfoThree',
      address: 'р-н. Шахритуз, джамоат пос. Шахритуз ул. И. Сомони 14',
      translatedAddress: 'aboutBranchAddressInfoThirtyTwo',
      lat:37.266736936748046,
      lng: 68.14375081776683,
      addressTitle: 'aboutBranchesPageTextEight',
      workingGraphic: "aboutBranchesPageTextTen",
      workingGraphicWorkingDays: "aboutBranchesPageTextEleven",
      workingGraphicDaysOff: "aboutBranchesPageTextTwelve",
      contacts: "aboutBranchesPageTextThirteen",
      contactsEmail: "aboutBranchesPageTextFifteen",
      services: "aboutBranchesPageTextSixteen",
      service: "aboutBranchesPageTextSeventeen",
    },
    {
      title: 'aboutBranchAddressInfoThree',
      address: 'р-н. Шахритуз, ул. И. Сомони 1 (рынок ООО “Ином”)',
      translatedAddress: 'aboutBranchAddressInfoThirtyThree',
      lat: 37.27091352113215,
      lng: 68.14780437476817,
      addressTitle: 'aboutBranchesPageTextEight',
      workingGraphic: "aboutBranchesPageTextTen",
      workingGraphicWorkingDays: "aboutBranchesPageTextEleven",
      workingGraphicDaysOff: "aboutBranchesPageTextTwelve",
      contacts: "aboutBranchesPageTextThirteen",
      contactsEmail: "aboutBranchesPageTextFifteen",
      services: "aboutBranchesPageTextSixteen",
      service: "aboutBranchesPageTextSeventeen",
    },
    {
      title: 'aboutBranchAddressInfoThree',
      address: 'р-н. А.Джоми, ул. Сомониён 14',
      translatedAddress: 'aboutBranchAddressInfoThirtyFour',
      lat: 37.947684777890096,
      lng: 68.79507545163665,
      addressTitle: 'aboutBranchesPageTextEight',
      workingGraphic: "aboutBranchesPageTextTen",
      workingGraphicWorkingDays: "aboutBranchesPageTextEleven",
      workingGraphicDaysOff: "aboutBranchesPageTextTwelve",
      contacts: "aboutBranchesPageTextThirteen",
      contactsEmail: "aboutBranchesPageTextFifteen",
      services: "aboutBranchesPageTextSixteen",
      service: "aboutBranchesPageTextSeventeen",
    },
    {
      title: 'aboutBranchAddressInfoThree',
      address: 'р-н. Хуросон, пос. Уяли, джамоат Айни',
      translatedAddress: 'aboutBranchAddressInfoThirtyFive',
      lat: 37.265942940978356,
      lng: 68.14375347810767,
      addressTitle: 'aboutBranchesPageTextEight',
      workingGraphic: "aboutBranchesPageTextTen",
      workingGraphicWorkingDays: "aboutBranchesPageTextEleven",
      workingGraphicDaysOff: "aboutBranchesPageTextTwelve",
      contacts: "aboutBranchesPageTextThirteen",
      contactsEmail: "aboutBranchesPageTextFifteen",
      services: "aboutBranchesPageTextSixteen",
      service: "aboutBranchesPageTextSeventeen",
    },
    {
      title: 'aboutBranchAddressInfoThree',
      address: 'р-н. Кубодиён, ул. Титов 2',
      translatedAddress: 'aboutBranchAddressInfoThirtySix',
      lat: 37.40440211688423,
      lng: 68.18330518555403,
      addressTitle: 'aboutBranchesPageTextEight',
      workingGraphic: "aboutBranchesPageTextTen",
      workingGraphicWorkingDays: "aboutBranchesPageTextEleven",
      workingGraphicDaysOff: "aboutBranchesPageTextTwelve",
      contacts: "aboutBranchesPageTextThirteen",
      contactsEmail: "aboutBranchesPageTextFifteen",
      services: "aboutBranchesPageTextSixteen",
      service: "aboutBranchesPageTextSeventeen",
    },
    {
      title: 'aboutBranchAddressInfoThree',
      address: 'р-н. Джайхун, ул. А. Беруни 1',
      translatedAddress: 'aboutBranchAddressInfoThirtySeven',
      lat: 37.35166676239271,
      lng: 68.67855543992928,
      addressTitle: 'aboutBranchesPageTextEight',
      workingGraphic: "aboutBranchesPageTextTen",
      workingGraphicWorkingDays: "aboutBranchesPageTextEleven",
      workingGraphicDaysOff: "aboutBranchesPageTextTwelve",
      contacts: "aboutBranchesPageTextThirteen",
      contactsEmail: "aboutBranchesPageTextFifteen",
      services: "aboutBranchesPageTextSixteen",
      service: "aboutBranchesPageTextSeventeen",
    },
    {
      title: 'aboutBranchAddressInfoThree',
      address: 'р-н. Шахритуз, ул. И. Сомони 10',
      translatedAddress: 'aboutBranchAddressInfoThirtyEight',
      lat: 37.264941,
      lng: 68.142894,
      addressTitle: 'aboutBranchesPageTextEight',
      workingGraphic: "aboutBranchesPageTextTen",
      workingGraphicWorkingDays: "aboutBranchesPageTextEleven",
      workingGraphicDaysOff: "aboutBranchesPageTextTwelve",
      contacts: "aboutBranchesPageTextThirteen",
      contactsEmail: "aboutBranchesPageTextFifteen",
      services: "aboutBranchesPageTextSixteen",
      service: "aboutBranchesPageTextSeventeen",
    },
    {
      title: 'aboutBranchAddressInfoThree',
      address: 'р-н. Дусти, джамоат Нури Вахш, село Джангалпарвар',
      translatedAddress: 'aboutBranchAddressInfoThirtyNine',
      lat: 37.533220528806446,
      lng: 68.4747486264298,
      addressTitle: 'aboutBranchesPageTextEight',
      workingGraphic: "aboutBranchesPageTextTen",
      workingGraphicWorkingDays: "aboutBranchesPageTextEleven",
      workingGraphicDaysOff: "aboutBranchesPageTextTwelve",
      contacts: "aboutBranchesPageTextThirteen",
      contactsEmail: "aboutBranchesPageTextFifteen",
      services: "aboutBranchesPageTextSixteen",
      service: "aboutBranchesPageTextSeventeen",
    },
    {
      title: 'aboutBranchAddressInfoThree',
      address: 'р-н. Ёвон, джамоат пос. хаёти Нав, село А.Навои',
      translatedAddress: 'aboutBranchAddressInfoForty',
      lat: 38.15845610998668,
      lng: 68.86280611455751,
      addressTitle: 'aboutBranchesPageTextEight',
      workingGraphic: "aboutBranchesPageTextTen",
      workingGraphicWorkingDays: "aboutBranchesPageTextEleven",
      workingGraphicDaysOff: "aboutBranchesPageTextTwelve",
      contacts: "aboutBranchesPageTextThirteen",
      contactsEmail: "aboutBranchesPageTextFifteen",
      services: "aboutBranchesPageTextSixteen",
      service: "aboutBranchesPageTextSeventeen",
    },
    {
      title: 'aboutBranchAddressInfoThree',
      address: 'р-н. Дж. Балхи, ул. Сино 24',
      translatedAddress: 'aboutBranchAddressInfoFortyOne',
      lat: 38.419035734912605,
      lng: 68.9510612406925,
      addressTitle: 'aboutBranchesPageTextEight',
      workingGraphic: "aboutBranchesPageTextTen",
      workingGraphicWorkingDays: "aboutBranchesPageTextEleven",
      workingGraphicDaysOff: "aboutBranchesPageTextTwelve",
      contacts: "aboutBranchesPageTextThirteen",
      contactsEmail: "aboutBranchesPageTextFifteen",
      services: "aboutBranchesPageTextSixteen",
      service: "aboutBranchesPageTextSeventeen",
    },
    {
      title: 'aboutBranchAddressInfoThree',
      address: 'р-н. Пандж, джамоат пос. Пандж, ул. 50 солагии кушунхои сархади 32/2',
      translatedAddress: 'aboutBranchAddressInfoFortyTwo',
      lat: 37.231909966236145,
      lng: 69.09521797219324,
      addressTitle: 'aboutBranchesPageTextEight',
      workingGraphic: "aboutBranchesPageTextTen",
      workingGraphicWorkingDays: "aboutBranchesPageTextEleven",
      workingGraphicDaysOff: "aboutBranchesPageTextTwelve",
      contacts: "aboutBranchesPageTextThirteen",
      contactsEmail: "aboutBranchesPageTextFifteen",
      services: "aboutBranchesPageTextSixteen",
      service: "aboutBranchesPageTextSeventeen",
    },
    {
      title: 'aboutBranchAddressInfoThree',
      address: 'р-н. Пандж, ул. 50 солагии кушунхои сархади 34/7',
      translatedAddress: 'aboutBranchAddressInfoFortyThree',
      lat: 37.23202660984037,
      lng: 69.09504978402842,
      addressTitle: 'aboutBranchesPageTextEight',
      workingGraphic: "aboutBranchesPageTextTen",
      workingGraphicWorkingDays: "aboutBranchesPageTextEleven",
      workingGraphicDaysOff: "aboutBranchesPageTextTwelve",
      contacts: "aboutBranchesPageTextThirteen",
      contactsEmail: "aboutBranchesPageTextFifteen",
      services: "aboutBranchesPageTextSixteen",
      service: "aboutBranchesPageTextSeventeen",
    },
    {
      title: 'aboutBranchAddressInfoThree',
      address: 'р-н. Пандж, джамоат пос. Пандж, ул. Рудаки',
      translatedAddress: 'aboutBranchAddressInfoFortyFour',
      lat: 37.23052618698867,
      lng: 69.10134162341434,
      addressTitle: 'aboutBranchesPageTextEight',
      workingGraphic: "aboutBranchesPageTextTen",
      workingGraphicWorkingDays: "aboutBranchesPageTextEleven",
      workingGraphicDaysOff: "aboutBranchesPageTextTwelve",
      contacts: "aboutBranchesPageTextThirteen",
      contactsEmail: "aboutBranchesPageTextFifteen",
      services: "aboutBranchesPageTextSixteen",
      service: "aboutBranchesPageTextSeventeen",
    },
    {
      title: 'aboutBranchAddressInfoThree',
      address: 'р-н. Шахритуз, ул. И. Сомони 26',
      translatedAddress: 'aboutBranchAddressInfoFortyFive',
      lat: 37.270929095723915,
      lng: 68.14781389850828,
      addressTitle: 'aboutBranchesPageTextEight',
      workingGraphic: "aboutBranchesPageTextTen",
      workingGraphicWorkingDays: "aboutBranchesPageTextEleven",
      workingGraphicDaysOff: "aboutBranchesPageTextTwelve",
      contacts: "aboutBranchesPageTextThirteen",
      contactsEmail: "aboutBranchesPageTextFifteen",
      services: "aboutBranchesPageTextSixteen",
      service: "aboutBranchesPageTextSeventeen",
    },
    {
      title: 'aboutBranchAddressInfoThree',
      address: 'р-н. Восеъ, пос. Хулбук, ул. Султони Кабир 82',
      translatedAddress: 'aboutBranchAddressInfoFortySix',
      lat: 37.80567580198357,
      lng: 69.63665915960213,
      addressTitle: 'aboutBranchesPageTextEight',
      workingGraphic: "aboutBranchesPageTextTen",
      workingGraphicWorkingDays: "aboutBranchesPageTextEleven",
      workingGraphicDaysOff: "aboutBranchesPageTextTwelve",
      contacts: "aboutBranchesPageTextThirteen",
      contactsEmail: "aboutBranchesPageTextFifteen",
      services: "aboutBranchesPageTextSixteen",
      service: "aboutBranchesPageTextSeventeen",
    },
  ]
}
